class CabinetDetail < ActiveRecord::Base
  # Validations
  validates :name, :street, :zipcode, :town, :tel, presence: true
  validates_format_of :tel, :with => /[0,0][1-9]\s(\d{2}\s)*\d{2}/

  # Relationships
  belongs_to :user, optional: true

  def ziptown
    "#{zipcode} - #{town}"
  end

  SPECIALTIES = [
    :addictologie,
    :alcoologie,
    :algologie,
    :allergologie,
    :anatomie_et_cytologie_pathologiques,
    :andrologie,
    :anesthesiologie_reanimation_chirurgicale,
    :angiologie,
    :biochimie,
    :biologie_medicale_et_physiologie,
    :cardiologie,
    :chirurgie,
    :chirurgie_digestive,
    :chirurgie_infantile,
    :chirurgie_maxillo_faciale_et_stomatologie,
    :chirurgie_orthopedique_et_traumatologique,
    :chirurgie_plastique,
    :chirurgie_thoracique_et_cardio_vasculaire,
    :chirurgie_urologique,
    :chirurgie_vasculaire,
    :chirurgie_viscerale,
    :contactologie,
    :coronarographie,
    :dentisterie,
    :dermatologie_et_venereologie,
    :endocrinologie_et_metabolisme,
    :explorations_fonctionnelles,
    :gastro_enterologie_et_hepatologie,
    :genetique,
    :geriatrie,
    :gynecologie_obstetrique,
    :hematologie,
    :hygiene_hospitaliere,
    :information_medicale,
    :maladies_infectieuses_et_tropicales,
    :medecine_du_travail,
    :medecine_generale,
    :medecine_interne,
    :medecine_legale,
    :medecine_nucleaire,
    :medecine_physique_et_de_readaptation,
    :neonatologie,
    :nephrologie,
    :neurochirurgie,
    :neurologie,
    :neuropediatrie,
    :neuropsychiatrie,
    :odontologie,
    :oncologie,
    :ophtalmologie,
    :orthodontie,
    :orthopedie,
    :orthophonie,
    :orthoptie,
    :osteopathie,
    :oto_rhino_laryngologie,
    :otologie,
    :otoneurologie,
    :parodontie,
    :parodontologie,
    :pediatrie,
    :pedodontie,
    :pedopsychiatrie,
    :pharmacie,
    :pharmacologie,
    :phlebologie,
    :pneumologie,
    :posturologie,
    :proctologie,
    :psychiatrie,
    :radiologie,
    :radiotherapie,
    :reanimation_medicale,
    :rhumatologie,
    :samu_smur,
    :sante_publique_et_medecine_sociale,
    :soins_palliatifs,
    :stomatologie,
    :strabologie,
    :tabacologie,
    :urgences,
    :urologie,
    :venereologie
  ]

end
